name: fieldmaps-hosted

services:
    api:
        build: ../backend
        ports:
            - "127.0.0.1:8000:8000"
        volumes:
            - ../backend/config.hosted.json:/app/config.local.json:ro
            - fieldmaps_api_secrets:/run/fieldmaps-secrets:ro

volumes:
    fieldmaps_api_secrets:
        external: true
        name: fieldmaps_hosted_api_secrets
