import type { LngLatBounds, StyleSpecification } from "@maplibre/maplibre-react-native";
import type { FeatureCollection } from "geojson";
import { Image } from "react-native";
import { z } from "zod";
import type { Coordinate } from "../domain/observation";
import type { SiteZone } from "./sample-site";
import equipmentData from "./sites/fall-creek/equipment.json";
import siteData from "./sites/fall-creek/site.json";
import surfacesData from "./sites/fall-creek/surfaces.json";
import treesData from "./sites/fall-creek/trees.json";

/**
 * Fall Creek Elementary playground, Ithaca: Weronika Kosciolek's QGIS drawings
 * (DECA_FALCR26001) and drone orthomosaic, relocated from where the project saved them. Files
 * under `sites/fall-creek/` are generated by `qgis/fall-creek/build.sh`; regenerate, don't edit.
 */

const lngLat = z.tuple([z.number(), z.number()]);
const site = z
  .object({
    centre: lngLat,
    bounds: z.tuple([z.number(), z.number(), z.number(), z.number()]),
    zone: z.object({
      west: z.number(),
      south: z.number(),
      east: z.number(),
      north: z.number(),
      zoom: z.number(),
    }),
    aerial: z.object({ corners: z.tuple([lngLat, lngLat, lngLat, lngLat]), matte: z.string() }),
  })
  .parse(siteData);

export const fallCreekCentre: Coordinate = site.centre;
export const fallCreekBounds: LngLatBounds = site.bounds;

/** No observation zones are defined for this site yet, so the one zone is the whole playground. */
export const fallCreekZone: SiteZone = {
  id: "A",
  label: "Zone A · Whole playground",
  centre: site.centre,
  ...site.zone,
};

export const fallCreekEquipment = equipmentData as FeatureCollection;
export const fallCreekTrees = treesData as FeatureCollection;
export const fallCreekZoneGeometry: FeatureCollection = {
  type: "FeatureCollection",
  features: [
    {
      type: "Feature",
      properties: { kind: "zone", id: fallCreekZone.id, label: fallCreekZone.label },
      geometry: {
        type: "Polygon",
        coordinates: [
          [
            [site.zone.west, site.zone.south],
            [site.zone.east, site.zone.south],
            [site.zone.east, site.zone.north],
            [site.zone.west, site.zone.north],
            [site.zone.west, site.zone.south],
          ],
        ],
      },
    },
  ],
};

/** Ground surfaces in QGIS drawing order, bottom first, kept dark so observations read first. */
const surfaces = [
  { kind: "dirt", fill: "#2c2a22", edge: "#3d3a2f" },
  { kind: "path", fill: "#2b2d3b", edge: "#3c3f52" },
  { kind: "blacktop", fill: "#22232b", edge: "#35374a" },
  { kind: "mulch", fill: "#2d2520", edge: "#3f342c" },
  { kind: "grass", fill: "#1e2a23", edge: "#2b3b30" },
] as const;

export const fallCreekPlan: StyleSpecification = {
  version: 8,
  name: "Fall Creek plan base",
  sources: { surfaces: { type: "geojson", data: surfacesData as FeatureCollection } },
  layers: [
    { id: "background", type: "background", paint: { "background-color": "#1b1d2b" } },
    ...surfaces.map(({ kind, fill, edge }) => ({
      id: `surface-${kind}`,
      type: "fill" as const,
      source: "surfaces",
      filter: ["==", "kind", kind] as ["==", string, string],
      paint: { "fill-color": fill, "fill-outline-color": edge },
    })),
  ],
};

/**
 * The drone photo sits in the style rather than an ImageSource component: the style parser keeps
 * corner coordinates in double precision, where the iOS component rounds them to floats.
 */
export const fallCreekAerial: StyleSpecification = {
  version: 8,
  name: "Fall Creek drone orthomosaic",
  sources: {
    aerial: {
      type: "image",
      url: Image.resolveAssetSource(require("./sites/fall-creek/aerial.jpg")).uri,
      coordinates: site.aerial.corners,
    },
  },
  layers: [
    { id: "background", type: "background", paint: { "background-color": site.aerial.matte } },
    { id: "aerial", type: "raster", source: "aerial" },
  ],
};
